/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Boletim.java
 *
 * Created on 05/06/2016, 12:45:51
 */
package Visão;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.util.*;
import javax.swing.Timer;

/**
 *
 * @author Antonio Nunes
 */
public class Boletim extends javax.swing.JFrame {

    /** Creates new form Boletim */
    public Boletim() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPPortugues = new javax.swing.JPanel();
        Portugues = new javax.swing.JLabel();
        jPMatematica = new javax.swing.JPanel();
        Matematica = new javax.swing.JLabel();
        jPCiencias = new javax.swing.JPanel();
        Ciencias = new javax.swing.JLabel();
        jPHistoria = new javax.swing.JPanel();
        Historia = new javax.swing.JLabel();
        jPReligiao = new javax.swing.JPanel();
        Religiao = new javax.swing.JLabel();
        jPGeografia = new javax.swing.JPanel();
        Geografia = new javax.swing.JLabel();
        jPComponentesCurriculares = new javax.swing.JPanel();
        Componentes = new javax.swing.JLabel();
        Curriculares = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        f4 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        f2 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        f5 = new javax.swing.JTextField();
        f6 = new javax.swing.JTextField();
        f7 = new javax.swing.JTextField();
        f8 = new javax.swing.JTextField();
        f12 = new javax.swing.JTextField();
        f11 = new javax.swing.JTextField();
        f10 = new javax.swing.JTextField();
        f9 = new javax.swing.JTextField();
        f13 = new javax.swing.JTextField();
        f14 = new javax.swing.JTextField();
        f15 = new javax.swing.JTextField();
        f16 = new javax.swing.JTextField();
        f20 = new javax.swing.JTextField();
        f19 = new javax.swing.JTextField();
        f18 = new javax.swing.JTextField();
        f17 = new javax.swing.JTextField();
        f21 = new javax.swing.JTextField();
        f22 = new javax.swing.JTextField();
        f23 = new javax.swing.JTextField();
        f24 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jPanel22 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        m1 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        m7 = new javax.swing.JTextField();
        m8 = new javax.swing.JTextField();
        m10 = new javax.swing.JTextField();
        m11 = new javax.swing.JTextField();
        m13 = new javax.swing.JTextField();
        m14 = new javax.swing.JTextField();
        m16 = new javax.swing.JTextField();
        m17 = new javax.swing.JTextField();
        m18 = new javax.swing.JComboBox();
        m9 = new javax.swing.JComboBox();
        m3 = new javax.swing.JComboBox();
        m12 = new javax.swing.JComboBox();
        m6 = new javax.swing.JComboBox();
        m15 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        j4 = new javax.swing.JTextField();
        j8 = new javax.swing.JTextField();
        j7 = new javax.swing.JTextField();
        j6 = new javax.swing.JTextField();
        j5 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j9 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j19 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        Data = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        Hora = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14));
        jLabel1.setText("Boletim escolar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(459, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(438, 438, 438))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Nome :");

        jLabel3.setText("Escola :");

        jLabel4.setText("Nº :");

        jLabel5.setText("Ano :");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jPPortugues.setBackground(new java.awt.Color(255, 255, 255));
        jPPortugues.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Portugues.setFont(new java.awt.Font("Arial", 0, 10));
        Portugues.setText("Português");

        javax.swing.GroupLayout jPPortuguesLayout = new javax.swing.GroupLayout(jPPortugues);
        jPPortugues.setLayout(jPPortuguesLayout);
        jPPortuguesLayout.setHorizontalGroup(
            jPPortuguesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPPortuguesLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Portugues, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPPortuguesLayout.setVerticalGroup(
            jPPortuguesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPortuguesLayout.createSequentialGroup()
                .addComponent(Portugues, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPPortugues);
        jPPortugues.setBounds(30, 79, 108, 30);

        jPMatematica.setBackground(new java.awt.Color(255, 255, 255));
        jPMatematica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Matematica.setFont(new java.awt.Font("Arial", 0, 10));
        Matematica.setText("Matemática");

        javax.swing.GroupLayout jPMatematicaLayout = new javax.swing.GroupLayout(jPMatematica);
        jPMatematica.setLayout(jPMatematicaLayout);
        jPMatematicaLayout.setHorizontalGroup(
            jPMatematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPMatematicaLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Matematica, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPMatematicaLayout.setVerticalGroup(
            jPMatematicaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Matematica, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel4.add(jPMatematica);
        jPMatematica.setBounds(30, 110, 108, 40);

        jPCiencias.setBackground(new java.awt.Color(255, 255, 255));
        jPCiencias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Ciencias.setFont(new java.awt.Font("Arial", 0, 10));
        Ciencias.setText("Ciências");

        javax.swing.GroupLayout jPCienciasLayout = new javax.swing.GroupLayout(jPCiencias);
        jPCiencias.setLayout(jPCienciasLayout);
        jPCienciasLayout.setHorizontalGroup(
            jPCienciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPCienciasLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Ciencias, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPCienciasLayout.setVerticalGroup(
            jPCienciasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Ciencias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel4.add(jPCiencias);
        jPCiencias.setBounds(30, 150, 108, 40);

        jPHistoria.setBackground(new java.awt.Color(255, 255, 255));
        jPHistoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Historia.setFont(new java.awt.Font("Arial", 0, 10));
        Historia.setText("História");

        javax.swing.GroupLayout jPHistoriaLayout = new javax.swing.GroupLayout(jPHistoria);
        jPHistoria.setLayout(jPHistoriaLayout);
        jPHistoriaLayout.setHorizontalGroup(
            jPHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPHistoriaLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(Historia, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPHistoriaLayout.setVerticalGroup(
            jPHistoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Historia, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel4.add(jPHistoria);
        jPHistoria.setBounds(30, 190, 108, 40);

        jPReligiao.setBackground(new java.awt.Color(255, 255, 255));
        jPReligiao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Religiao.setFont(new java.awt.Font("Arial", 0, 10));
        Religiao.setText("Religião");

        javax.swing.GroupLayout jPReligiaoLayout = new javax.swing.GroupLayout(jPReligiao);
        jPReligiao.setLayout(jPReligiaoLayout);
        jPReligiaoLayout.setHorizontalGroup(
            jPReligiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPReligiaoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(Religiao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPReligiaoLayout.setVerticalGroup(
            jPReligiaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Religiao, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel4.add(jPReligiao);
        jPReligiao.setBounds(30, 230, 108, 40);

        jPGeografia.setBackground(new java.awt.Color(255, 255, 255));
        jPGeografia.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Geografia.setFont(new java.awt.Font("Arial", 0, 10));
        Geografia.setText("Geografia");

        javax.swing.GroupLayout jPGeografiaLayout = new javax.swing.GroupLayout(jPGeografia);
        jPGeografia.setLayout(jPGeografiaLayout);
        jPGeografiaLayout.setHorizontalGroup(
            jPGeografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPGeografiaLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(Geografia, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPGeografiaLayout.setVerticalGroup(
            jPGeografiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Geografia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );

        jPanel4.add(jPGeografia);
        jPGeografia.setBounds(30, 270, 108, 40);

        jPComponentesCurriculares.setBackground(new java.awt.Color(255, 255, 255));
        jPComponentesCurriculares.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Componentes.setFont(new java.awt.Font("Arial", 0, 10));
        Componentes.setText("Componentes");

        Curriculares.setFont(new java.awt.Font("Arial", 0, 10));
        Curriculares.setText("Curriculares");

        javax.swing.GroupLayout jPComponentesCurricularesLayout = new javax.swing.GroupLayout(jPComponentesCurriculares);
        jPComponentesCurriculares.setLayout(jPComponentesCurricularesLayout);
        jPComponentesCurricularesLayout.setHorizontalGroup(
            jPComponentesCurricularesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComponentesCurricularesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPComponentesCurricularesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Curriculares)
                    .addComponent(Componentes, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPComponentesCurricularesLayout.setVerticalGroup(
            jPComponentesCurricularesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPComponentesCurricularesLayout.createSequentialGroup()
                .addComponent(Componentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Curriculares, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPComponentesCurriculares);
        jPComponentesCurriculares.setBounds(30, 30, 108, 42);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12));
        jLabel7.setText("Faltas");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 1, 54, -1));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel12.setText("1° Bim");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("2° Bim");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 40));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel14.setText("3° Bim");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel14)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 60, 40));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel15.setText("4° Bim");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel15)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel6.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 60, 40));
        jPanel6.add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 60, 28));
        jPanel6.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, 28));
        jPanel6.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 28));
        jPanel6.add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 28));
        jPanel6.add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, 28));
        jPanel6.add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 28));
        jPanel6.add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 60, 28));
        jPanel6.add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 60, 28));
        jPanel6.add(f12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 60, 28));
        jPanel6.add(f11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 60, 28));
        jPanel6.add(f10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, 28));
        jPanel6.add(f9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 28));
        jPanel6.add(f13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 28));
        jPanel6.add(f14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 60, 28));
        jPanel6.add(f15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 60, 28));
        jPanel6.add(f16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 60, 28));
        jPanel6.add(f20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, 28));
        jPanel6.add(f19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 60, 28));
        jPanel6.add(f18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 28));
        jPanel6.add(f17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 28));
        jPanel6.add(f21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, 28));
        jPanel6.add(f22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 60, 28));
        jPanel6.add(f23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 60, 28));
        jPanel6.add(f24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 60, 28));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(null);

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("FINAL");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 15, Short.MAX_VALUE)))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel7.add(jPanel20);
        jPanel20.setBounds(170, 30, 60, 40);

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel21.setText("TOTAL DE FALTAS");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 98, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 5, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 5, Short.MAX_VALUE)))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel21)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel7.add(jPanel21);
        jPanel21.setBounds(70, 30, 100, 40);

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel22.setText("MEDIA");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(0, 13, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 13, Short.MAX_VALUE)))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel22Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel22)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel7.add(jPanel22);
        jPanel22.setBounds(10, 30, 60, 40);
        jPanel7.add(m1);
        m1.setBounds(10, 80, 60, 30);
        jPanel7.add(m2);
        m2.setBounds(70, 80, 100, 30);
        jPanel7.add(m4);
        m4.setBounds(10, 120, 60, 30);
        jPanel7.add(m5);
        m5.setBounds(70, 120, 100, 30);
        jPanel7.add(m7);
        m7.setBounds(10, 160, 60, 30);
        jPanel7.add(m8);
        m8.setBounds(70, 160, 100, 30);
        jPanel7.add(m10);
        m10.setBounds(10, 200, 60, 30);
        jPanel7.add(m11);
        m11.setBounds(70, 200, 100, 30);
        jPanel7.add(m13);
        m13.setBounds(10, 240, 60, 30);
        jPanel7.add(m14);
        m14.setBounds(70, 240, 100, 30);
        jPanel7.add(m16);
        m16.setBounds(10, 280, 60, 30);
        jPanel7.add(m17);
        m17.setBounds(70, 280, 100, 30);

        m18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Reprovado" }));
        jPanel7.add(m18);
        m18.setBounds(170, 280, 60, 30);

        m9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Reprovado" }));
        jPanel7.add(m9);
        m9.setBounds(170, 160, 60, 30);

        m3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Reprovado" }));
        jPanel7.add(m3);
        m3.setBounds(170, 80, 60, 30);

        m12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Reprovado" }));
        jPanel7.add(m12);
        m12.setBounds(170, 200, 60, 30);

        m6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Reprovado" }));
        m6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m6ActionPerformed(evt);
            }
        });
        jPanel7.add(m6);
        m6.setBounds(170, 120, 60, 30);

        m15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprovado", "Reprovado" }));
        jPanel7.add(m15);
        m15.setBounds(170, 240, 60, 30);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12));
        jLabel8.setText("Notas");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 1, 54, -1));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel16.setText("1° Bim");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 40));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("2° Bim");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel17Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel17)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 40));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setText("3° Bim");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel18Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 60, 40));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("4° Bim");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(0, 14, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 14, Short.MAX_VALUE)))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(0, 12, Short.MAX_VALUE)
                    .addComponent(jLabel19)
                    .addGap(0, 12, Short.MAX_VALUE)))
        );

        jPanel8.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, 60, 40));
        jPanel8.add(j1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, 28));
        jPanel8.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 60, 28));
        jPanel8.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 60, 28));
        jPanel8.add(j4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 60, 28));
        jPanel8.add(j8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 60, 28));
        jPanel8.add(j7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 60, 28));
        jPanel8.add(j6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 60, 28));
        jPanel8.add(j5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 60, 28));
        jPanel8.add(j12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 60, 28));
        jPanel8.add(j11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 60, 28));
        jPanel8.add(j10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 60, 28));
        jPanel8.add(j9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 60, 28));
        jPanel8.add(j16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 60, 28));
        jPanel8.add(j15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 60, 28));
        jPanel8.add(j14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 60, 28));
        jPanel8.add(j13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 60, 28));
        jPanel8.add(j20, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 60, 28));
        jPanel8.add(j19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 60, 28));
        jPanel8.add(j18, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 28));
        jPanel8.add(j17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 60, 28));
        jPanel8.add(j24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 60, 28));
        jPanel8.add(j23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 60, 28));
        jPanel8.add(j22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 60, 28));
        jPanel8.add(j21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 60, 28));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 935, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/concluido2.png"))); // NOI18N
        jButton1.setText("Concluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/botao-apagar.png"))); // NOI18N
        jButton3.setText("Apagar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 550));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jPanel11.setLayout(null);

        Data.setFont(new java.awt.Font("Arial", 0, 12));
        Data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(Data);
        Data.setBounds(-10, -10, 140, 50);

        jPanel5.add(jPanel11);
        jPanel11.setBounds(1000, 0, 120, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/calendar-icon-512x512.png"))); // NOI18N
        jPanel5.add(jLabel6);
        jLabel6.setBounds(970, 0, 30, 30);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        Hora.setFont(new java.awt.Font("Arial", 0, 12));
        Hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(Hora);
        Hora.setBounds(0, 0, 120, 30);

        jPanel5.add(jPanel10);
        jPanel10.setBounds(820, 0, 120, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Relogio1122'.png"))); // NOI18N
        jPanel5.add(jLabel9);
        jLabel9.setBounds(790, 0, 30, 30);

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 1150, 30));

        jMenu1.setText("Inicio");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/home.png"))); // NOI18N
        jMenuItem11.setText("Inicio");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alunos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/addp.png"))); // NOI18N
        jMenuItem1.setText("Cadastra alunos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone_boletim_online.gif"))); // NOI18N
        jMenuItem5.setText("Criar boletim");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/aaf.png"))); // NOI18N
        jMenu6.setText("Alunos cadastrados");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/figura468.png"))); // NOI18N
        jMenuItem2.setText("Ficha Pessoal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/link1.png"))); // NOI18N
        jMenuItem3.setText("Historico escolar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Frequencia");
        jMenu6.add(jMenuItem4);

        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Professores");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/adda.png"))); // NOI18N
        jMenuItem6.setText("Cadastra professores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon-entrar.png"))); // NOI18N
        jMenu7.setText("Professores cadastrados");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone-unidade-proposta-didatica.png"))); // NOI18N
        jMenuItem7.setText("Ficha Pessoal");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_news.png"))); // NOI18N
        jMenuItem8.setText("Curriculo");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem8);

        jMenu3.add(jMenu7);

        jMenuBar1.add(jMenu3);

        jMenu8.setText("Alarme");

        jMenuItem12.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/relogio.png"))); // NOI18N
        jMenuItem12.setText("Alarme");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem12);

        jMenuBar1.add(jMenu8);

        jMenu4.setText("Ajuda");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1334.png"))); // NOI18N
        jMenuItem9.setText("Ajuda");
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Sair");
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Cancelar.png"))); // NOI18N
        jMenuItem10.setText("Sair");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
            
}//GEN-LAST:event_jMenu1MouseClicked

private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
           
}//GEN-LAST:event_jMenu1ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
            CadastraAlunos a = new CadastraAlunos();
            a.setVisible(true);
            dispose();
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
            CadastraProfessor d = new CadastraProfessor ();
            d.setVisible(true);
            dispose();
            
}//GEN-LAST:event_jMenuItem6ActionPerformed

private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
            
}//GEN-LAST:event_jMenu5ActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButton3ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }    
        
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jMenuItem8ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jMenuItem7ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
Boletim e = new Boletim();
     e.setVisible(true);
     dispose();
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
            TelaPrincipal e = new TelaPrincipal();
            e.setVisible(true);
            dispose();
}//GEN-LAST:event_jMenuItem11ActionPerformed

private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
             SairBoletim e = new SairBoletim();
            e.setVisible(true);
}//GEN-LAST:event_jMenuItem10ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//Data
         Date dataSistema = new Date();
         SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
         Data.setText(formato.format(dataSistema));
         //Hora
         timer = new Timer(1000, new cronometro());
         timer.start();
}//GEN-LAST:event_formWindowOpened

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     SairBoletim e = new SairBoletim();
     e.setVisible(true);
             
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
             String Nome = jTextField1.getText();
             String Escola = jTextField3.getText();
             String Portugues1 = j1.getText();
             String Portugues2 = j2.getText();
             String Portugues3 = j3.getText();
             String Portugues4 = j4.getText();
             String Matematica1 = j5.getText();
             String Matematica2 = j6.getText();
             String Matematica3 = j7.getText();
             String Matematica4 = j8.getText();
             String Ciencias1 = j9.getText();
              String Ciencias2 = j10.getText();
              String Ciencias3 = j11.getText();
              String Ciencias4 = j12.getText();
              String Historia1 = j13.getText();
              String Historia2 = j14.getText();
              String Historia3 = j15.getText();
              String Historia4 = j16.getText();
              String Religiao1 = j17.getText();
              String Religiao2 = j18.getText();
              String Religiao3 = j19.getText();
              String Religiao4 = j20.getText();
              String Geografia1 = j21.getText();
              String Geografia2 = j22.getText();
              String Geografia3 = j23.getText();
              String Geografia4 = j24.getText();
              String Portugues1f = f1.getText();
             String Portugues2f = f2.getText();
             String Portugues3f = f3.getText();
             String Portugues4f = f4.getText();
             String Matematica1f = f5.getText();
             String Matematica2f = f6.getText();
             String Matematica3f = f7.getText();
             String Matematica4f = f8.getText();
             String Ciencias1f = f9.getText();
              String Ciencias2f = f10.getText();
              String Ciencias3f = f11.getText();
              String Ciencias4f = f12.getText();
              String Historia1f = f13.getText();
              String Historia2f = f14.getText();
              String Historia3f = f15.getText();
              String Historia4f = f16.getText();
              String Religiao1f = f17.getText();
              String Religiao2f = f18.getText();
              String Religiao3f = f19.getText();
              String Religiao4f = f20.getText();
              String Geografia1f = f21.getText();
              String Geografia2f = f22.getText();
              String Geografia3f = f23.getText();
              String Geografia4f = f24.getText();
              String Portugues1m = m1.getText();
             String Portugues2m = m2.getText();
             String Portugues3m = (String) m3.getSelectedItem();
             String Portugues4m = m4.getText();
             String Matematica1m = m5.getText();
             String Matematica2m = (String) m6.getSelectedItem();
             String Matematica3m = m7.getText();
             String Matematica4m = m8.getText();
             String Ciencias1m = (String) m9.getSelectedItem();
              String Ciencias2m = m10.getText();
              String Ciencias3m = m11.getText();
              String Ciencias4m = (String) m12.getSelectedItem();
              String Historia1m = m13.getText();
              String Historia2m = m14.getText();
              String Historia3m = (String) m15.getSelectedItem();
              String Historia4m = m16.getText();
              String Religiao1m = m17.getText();
              String Religiao2m = (String) m18.getSelectedItem();
            Document documento = new Document();       
            try {
                PdfWriter.getInstance(documento, new FileOutputStream("C:\\Users\\Antonio Nunes\\Desktop\\ProjetoSecretaria\\ProjetoSecretaria\\Boletim\\"+"Boletim de " +Nome+".pdf"));
                
    
                documento.open();
                documento.setPageSize(PageSize.A4);
                documento.add(new Paragraph("                                                              Boletim"));
                documento.add(new Paragraph("                                                                                                                 "));
                documento.add(new Paragraph("                                                Nome : " +Nome));
                documento.add(new Paragraph("                                                Escola :"+Escola));
                PdfPTable tab = new PdfPTable(12);
                PdfPCell Cabecalho = new PdfPCell(new Paragraph(""));
                Cabecalho.setColspan(1);
                Cabecalho.setHorizontalAlignment(Cabecalho.ALIGN_CENTER);
                PdfPCell Notas = new PdfPCell(new Paragraph("Notas"));
                Notas.setColspan(4);
                Notas.setHorizontalAlignment(Cabecalho.ALIGN_CENTER);
                PdfPCell Faltas = new PdfPCell(new Paragraph("Faltas"));
                Faltas.setColspan(4);
                Faltas.setHorizontalAlignment(Cabecalho.ALIGN_CENTER);
                PdfPCell Nda = new PdfPCell(new Paragraph(""));
                Nda.setColspan(3);
                tab.addCell(Cabecalho);
                tab.addCell(Notas);
                tab.addCell(Faltas);
                tab.addCell(Nda);
                tab.addCell("Componentes curriculres");
                tab.addCell("1º Bim");
                tab.addCell("2º Bim");
                tab.addCell("3º Bim");
                tab.addCell("4º Bim");
                tab.addCell("1º Bim");
                tab.addCell("2º Bim");
                tab.addCell("3º Bim");
                tab.addCell("4º Bim");
                tab.addCell("Media");
                tab.addCell("TotalDeFaltas");
                tab.addCell("Final");
                tab.addCell("Português");
                tab.addCell(Portugues1);
                tab.addCell(Portugues2);
                tab.addCell(Portugues3);
                tab.addCell(Portugues4);
                tab.addCell(Portugues1f);
                tab.addCell(Portugues2f);
                tab.addCell(Portugues3f);
                tab.addCell(Portugues4f);
                tab.addCell(Portugues1f);
                tab.addCell(Portugues2f);
                tab.addCell(Portugues3f);
                tab.addCell("Matemática");
                tab.addCell(Matematica1);
                tab.addCell(Matematica2);
                tab.addCell(Matematica3);
                tab.addCell(Matematica4);
                tab.addCell(Matematica1f);
                tab.addCell(Matematica2f);
                tab.addCell(Matematica3f);
                tab.addCell(Matematica4f);
                tab.addCell(Portugues4m);
                tab.addCell(Matematica1m);
                tab.addCell(Matematica2m);
                tab.addCell("Ciências");
                tab.addCell(Ciencias1);
                tab.addCell(Ciencias2);
                tab.addCell(Ciencias3);
                tab.addCell(Ciencias4);
                tab.addCell(Ciencias1f);
                tab.addCell(Ciencias2f);
                tab.addCell(Ciencias3f);
                tab.addCell(Ciencias4f);
                tab.addCell(Matematica3m);
                tab.addCell(Matematica4m);
                tab.addCell(Ciencias1m);
                tab.addCell("Hstória");
                tab.addCell(Historia1);
                tab.addCell(Historia2);
                tab.addCell(Historia3);
                tab.addCell(Historia4);
                tab.addCell(Historia1f);
                tab.addCell(Historia2f);
                tab.addCell(Historia3f);
                tab.addCell(Historia4f);
                tab.addCell(Ciencias2m);
                tab.addCell(Ciencias3m);
                tab.addCell(Ciencias4m);
                tab.addCell("Religião");
                tab.addCell(Religiao1);
                tab.addCell(Religiao2);
                tab.addCell(Religiao3);
                tab.addCell(Religiao4);
                tab.addCell(Religiao1f);
                tab.addCell(Religiao2f);
                tab.addCell(Religiao3f);
                tab.addCell(Religiao4f);
                 tab.addCell(Historia1m);
                tab.addCell(Historia2m);
                tab.addCell(Historia3m);
                tab.addCell("Geografia");
                tab.addCell(Geografia1);
                tab.addCell(Geografia2);
                tab.addCell(Geografia3);
                tab.addCell(Geografia4);
                tab.addCell(Geografia1f);
                tab.addCell(Geografia2f);
                tab.addCell(Geografia3f);
                tab.addCell(Geografia4f);
                tab.addCell(Historia4m);
                 tab.addCell(Religiao1m);
                tab.addCell(Religiao2m);
                documento.add(tab);
                documento.close();
                
            }
            catch (DocumentException | FileNotFoundException ex) {
            }
            ConclusãoBoletim e = new ConclusãoBoletim();
            e.setVisible(true);
            dispose();
                    
}//GEN-LAST:event_jButton1ActionPerformed

private void m6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m6ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_m6ActionPerformed

private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
Alarme e = new Alarme();
    e.setVisible(true);
    dispose();
}//GEN-LAST:event_jMenuItem12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boletim.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Boletim().setVisible(true);
            }
        });
    }
    public class cronometro implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae) {
            GregorianCalendar tiempo = new GregorianCalendar();
          int h, m ,s;
          h=tiempo.get(Calendar.HOUR_OF_DAY);
          m=tiempo.get(Calendar.MINUTE);
          s=tiempo.get(Calendar.SECOND);
          Hora.setText(String.valueOf(h+":"+m+":"+s));
        }

        

    }
    private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Ciencias;
    private javax.swing.JLabel Componentes;
    private javax.swing.JLabel Curriculares;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Geografia;
    private javax.swing.JLabel Historia;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel Matematica;
    private javax.swing.JLabel Portugues;
    private javax.swing.JLabel Religiao;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f10;
    private javax.swing.JTextField f11;
    private javax.swing.JTextField f12;
    private javax.swing.JTextField f13;
    private javax.swing.JTextField f14;
    private javax.swing.JTextField f15;
    private javax.swing.JTextField f16;
    private javax.swing.JTextField f17;
    private javax.swing.JTextField f18;
    private javax.swing.JTextField f19;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f20;
    private javax.swing.JTextField f21;
    private javax.swing.JTextField f22;
    private javax.swing.JTextField f23;
    private javax.swing.JTextField f24;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField f4;
    private javax.swing.JTextField f5;
    private javax.swing.JTextField f6;
    private javax.swing.JTextField f7;
    private javax.swing.JTextField f8;
    private javax.swing.JTextField f9;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j19;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j3;
    private javax.swing.JTextField j4;
    private javax.swing.JTextField j5;
    private javax.swing.JTextField j6;
    private javax.swing.JTextField j7;
    private javax.swing.JTextField j8;
    private javax.swing.JTextField j9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPCiencias;
    private javax.swing.JPanel jPComponentesCurriculares;
    private javax.swing.JPanel jPGeografia;
    private javax.swing.JPanel jPHistoria;
    private javax.swing.JPanel jPMatematica;
    private javax.swing.JPanel jPPortugues;
    private javax.swing.JPanel jPReligiao;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m11;
    private javax.swing.JComboBox m12;
    private javax.swing.JTextField m13;
    private javax.swing.JTextField m14;
    private javax.swing.JComboBox m15;
    private javax.swing.JTextField m16;
    private javax.swing.JTextField m17;
    private javax.swing.JComboBox m18;
    private javax.swing.JTextField m2;
    private javax.swing.JComboBox m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JComboBox m6;
    private javax.swing.JTextField m7;
    private javax.swing.JTextField m8;
    private javax.swing.JComboBox m9;
    // End of variables declaration//GEN-END:variables
}
