package visao;
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Teste.java
 *
 * Created on 29/05/2016, 17:19:19
 */
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.*;
import javax.swing.Timer;

/**
 *
 * @author Antonio Nunes
 */
public class CadastraProfessor extends javax.swing.JFrame {
    

    /** Creates new form Teste */
    public CadastraProfessor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelDeRolagem = new javax.swing.JScrollPane();
        PainelPrincipal = new javax.swing.JPanel();
        DadosPessoais = new javax.swing.JLabel();
        NomeCompleto = new javax.swing.JLabel();
        jTNomeCompleto = new javax.swing.JTextField();
        Endereco = new javax.swing.JLabel();
        jTEndereco = new javax.swing.JTextField();
        Municipio = new javax.swing.JLabel();
        jTMunicipio = new javax.swing.JTextField();
        Cep = new javax.swing.JLabel();
        jfCep = new javax.swing.JFormattedTextField();
        Email = new javax.swing.JLabel();
        jTEmail = new javax.swing.JTextField();
        Cpf = new javax.swing.JLabel();
        jfCpf = new javax.swing.JFormattedTextField();
        Rg = new javax.swing.JLabel();
        jfRg = new javax.swing.JFormattedTextField();
        CargaHorariaSemanal = new javax.swing.JLabel();
        jfCargaHorariaSemanal = new javax.swing.JFormattedTextField();
        TempoDeServico = new javax.swing.JLabel();
        jfTempoDeServico = new javax.swing.JFormattedTextField();
        Banco = new javax.swing.JLabel();
        jCBBanco = new javax.swing.JComboBox();
        Conta = new javax.swing.JLabel();
        jfConta = new javax.swing.JFormattedTextField();
        Agencia = new javax.swing.JLabel();
        jfAgencia = new javax.swing.JFormattedTextField();
        Escolaridade = new javax.swing.JLabel();
        EnsinoMedio = new javax.swing.JLabel();
        jCBEnsinoMedio = new javax.swing.JComboBox();
        MConcluiuEm = new javax.swing.JLabel();
        jTMConcluiuEm = new javax.swing.JTextField();
        EnsinoSuperior = new javax.swing.JLabel();
        jCBEnsinoSuperior = new javax.swing.JComboBox();
        SConcluiuEm = new javax.swing.JLabel();
        jTSConcluiuEm = new javax.swing.JTextField();
        Status = new javax.swing.JLabel();
        jCBStatus = new javax.swing.JComboBox();
        Diretor = new javax.swing.JLabel();
        jCBDiretor = new javax.swing.JComboBox();
        Professor = new javax.swing.JLabel();
        jCBProfessor = new javax.swing.JComboBox();
        Outros = new javax.swing.JLabel();
        jCBOutros = new javax.swing.JComboBox();
        NivelDeAtuacao = new javax.swing.JLabel();
        jCBNivelDeAtuacao = new javax.swing.JComboBox();
        DisciplinaQueLeciona = new javax.swing.JLabel();
        jTDisciplinaQueLeciona = new javax.swing.JTextField();
        CursoDeLicenciaturaParaOQualFoiAprovado = new javax.swing.JLabel();
        jCBCursoDeLicenciaturaParaOQualFoiAprovaddo = new javax.swing.JComboBox();
        UniversidadeEmQueSeFormou = new javax.swing.JLabel();
        jTUniversidadeEmQueSeFormou = new javax.swing.JTextField();
        ModalidadeDoCurso = new javax.swing.JLabel();
        jCBModalidadeDoCurso = new javax.swing.JComboBox();
        jBProximo = new javax.swing.JButton();
        jBApagarTudo = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        Hora = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        Data = new javax.swing.JLabel();
        PlanoDeFundo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        PainelDeRolagem.setPreferredSize(new java.awt.Dimension(800, 1200));

        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DadosPessoais.setFont(new java.awt.Font("Arial Black", 0, 10)); // NOI18N
        DadosPessoais.setText("DADOS  PESSOAIS");
        PainelPrincipal.add(DadosPessoais, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 120, -1));

        NomeCompleto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NomeCompleto.setText("Nome completo :");
        PainelPrincipal.add(NomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 100, 20));

        jTNomeCompleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNomeCompletoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTNomeCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 240, -1));

        Endereco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Endereco.setText("Endereço :");
        PainelPrincipal.add(Endereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 70, 20));

        jTEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEnderecoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 270, -1));

        Municipio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Municipio.setText("Municipio :");
        PainelPrincipal.add(Municipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 60, 20));

        jTMunicipio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMunicipioActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTMunicipio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 150, -1));

        Cep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Cep.setText("CEP :");
        PainelPrincipal.add(Cep, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 34, 20));

        jfCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCepActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jfCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, 70, -1));

        Email.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Email.setText("E-mail :");
        PainelPrincipal.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 50, 20));

        jTEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTEmailActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 290, -1));

        Cpf.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Cpf.setText("CPF :");
        PainelPrincipal.add(Cpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 40, 20));

        jfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCpfActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, 80, 20));

        Rg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Rg.setText("RG :");
        PainelPrincipal.add(Rg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 30, 20));

        jfRg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfRgActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jfRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 180, -1));

        CargaHorariaSemanal.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CargaHorariaSemanal.setText("Carga horaria semanal :");
        PainelPrincipal.add(CargaHorariaSemanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 140, 40));

        jfCargaHorariaSemanal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfCargaHorariaSemanalActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jfCargaHorariaSemanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, 40, -1));

        TempoDeServico.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TempoDeServico.setText("Tempo de serviço :");
        PainelPrincipal.add(TempoDeServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 110, 40));

        jfTempoDeServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfTempoDeServicoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jfTempoDeServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 40, -1));

        Banco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Banco.setText("Banco :");
        PainelPrincipal.add(Banco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, 50, 20));

        jCBBanco.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banco do Brasil", "Caixa Ecônomica", "Santander", "Itaú", "Banco do Nordeste", "Bradesco" }));
        jCBBanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBBancoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 120, -1));

        Conta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Conta.setText("Conta :");
        PainelPrincipal.add(Conta, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 40, 40));

        jfConta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfContaActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jfConta, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 130, -1));

        Agencia.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Agencia.setText("Agência :");
        PainelPrincipal.add(Agencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 400, -1, 20));

        jfAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfAgenciaActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jfAgencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 80, -1));

        Escolaridade.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Escolaridade.setText("ESCOLARIDADE");
        PainelPrincipal.add(Escolaridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 110, -1));

        EnsinoMedio.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EnsinoMedio.setText("Ensino médio :");
        PainelPrincipal.add(EnsinoMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 90, 40));

        jCBEnsinoMedio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Completo", "Completo + adicionais" }));
        jCBEnsinoMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEnsinoMedioActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBEnsinoMedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 110, -1));

        MConcluiuEm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        MConcluiuEm.setText("Concluiu em :");
        PainelPrincipal.add(MConcluiuEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 510, 90, 20));

        jTMConcluiuEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTMConcluiuEmActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTMConcluiuEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, 50, -1));

        EnsinoSuperior.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        EnsinoSuperior.setText("Ensino superio :");
        PainelPrincipal.add(EnsinoSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, 90, 40));

        jCBEnsinoSuperior.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "bacharel", "Licenciatura curta", "Licenciatura", "tecnologia" }));
        jCBEnsinoSuperior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBEnsinoSuperiorActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBEnsinoSuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 550, 100, -1));

        SConcluiuEm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        SConcluiuEm.setText("Concluiu em :");
        PainelPrincipal.add(SConcluiuEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 550, -1, 20));

        jTSConcluiuEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTSConcluiuEmActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTSConcluiuEm, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 550, 50, -1));

        Status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Status.setText("Status :");
        PainelPrincipal.add(Status, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 100, 40));

        jCBStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Efetivo", "Comissionário" }));
        jCBStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBStatusActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 660, 110, -1));

        Diretor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Diretor.setText("Diretor :");
        PainelPrincipal.add(Diretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 100, 40));

        jCBDiretor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Escola", "Outros" }));
        jCBDiretor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBDiretorActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBDiretor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 660, 110, -1));

        Professor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Professor.setText("Professor :");
        PainelPrincipal.add(Professor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 690, 100, 40));

        jCBProfessor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Contato", "Em sala de aula ", "Fora de sala ", " " }));
        jCBProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBProfessorActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBProfessor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 700, 100, -1));

        Outros.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Outros.setText("Outros :");
        PainelPrincipal.add(Outros, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 690, 100, 40));

        jCBOutros.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Técnico" }));
        jCBOutros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBOutrosActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBOutros, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 700, 110, -1));

        NivelDeAtuacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NivelDeAtuacao.setText("Nível de atuação como professor :");
        PainelPrincipal.add(NivelDeAtuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 790, 200, 40));

        jCBNivelDeAtuacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ensino médio", "Ensino Infantil", "Ensino Fundamental - 5° a 6° série", "Ensino fundamental - Anos iniciais 1° a 4° série", "Instrutor" }));
        jCBNivelDeAtuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBNivelDeAtuacaoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBNivelDeAtuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 800, 170, -1));

        DisciplinaQueLeciona.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        DisciplinaQueLeciona.setText("Disciplina(s) que leciona :");
        PainelPrincipal.add(DisciplinaQueLeciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 830, 150, 40));

        jTDisciplinaQueLeciona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTDisciplinaQueLecionaActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTDisciplinaQueLeciona, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 840, 210, 24));

        CursoDeLicenciaturaParaOQualFoiAprovado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        CursoDeLicenciaturaParaOQualFoiAprovado.setText("Curso de licenciatura para o qual foi aprovado :");
        PainelPrincipal.add(CursoDeLicenciaturaParaOQualFoiAprovado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 870, 280, 40));

        jCBCursoDeLicenciaturaParaOQualFoiAprovaddo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Informática", "Artes", "Geografia", "História", "Administração ", "Enfermagem ", "Matemátca ", "Gramática ", "P. Textual", "Literatura", "Física ", "Química ", "E.Física", "Filosofiia", "Sociologia", "Biologia", "Espanhol", "Inglês", "P. de Vida ", "H.E", "F. para à Cidadania " }));
        jCBCursoDeLicenciaturaParaOQualFoiAprovaddo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBCursoDeLicenciaturaParaOQualFoiAprovaddoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBCursoDeLicenciaturaParaOQualFoiAprovaddo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 880, 100, -1));

        UniversidadeEmQueSeFormou.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        UniversidadeEmQueSeFormou.setText("Universidades em que se formou :");
        PainelPrincipal.add(UniversidadeEmQueSeFormou, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 910, 200, 40));

        jTUniversidadeEmQueSeFormou.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUniversidadeEmQueSeFormouActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jTUniversidadeEmQueSeFormou, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 920, 170, 24));

        ModalidadeDoCurso.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        ModalidadeDoCurso.setText("Modalidade do curso  :");
        PainelPrincipal.add(ModalidadeDoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 950, 140, 40));

        jCBModalidadeDoCurso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Presencial", "Distância" }));
        jCBModalidadeDoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBModalidadeDoCursoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jCBModalidadeDoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 960, 110, -1));

        jBProximo.setBackground(new java.awt.Color(255, 255, 255));
        jBProximo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/ico_seta_azul_direita.gif"))); // NOI18N
        jBProximo.setText("Proximo");
        jBProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jBProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 1020, 100, -1));

        jBApagarTudo.setBackground(new java.awt.Color(255, 255, 255));
        jBApagarTudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/botao-apagar.png"))); // NOI18N
        jBApagarTudo.setText("Apagar");
        jBApagarTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBApagarTudoActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jBApagarTudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 1020, 120, -1));

        jBCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jBCancelar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Cancelar.png"))); // NOI18N
        jBCancelar.setText("Sair");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        PainelPrincipal.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 1020, 80, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0)));
        jPanel10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.setLayout(null);

        Hora.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Hora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel10.add(Hora);
        Hora.setBounds(0, 0, 100, 30);

        jPanel2.add(jPanel10);
        jPanel10.setBounds(460, 0, 110, 30);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/calendar-icon-512x512.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(600, 0, 30, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Relogio1122'.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(430, 0, 30, 30);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51)));
        jPanel11.setLayout(null);

        Data.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Data.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel11.add(Data);
        Data.setBounds(-10, -10, 140, 50);

        jPanel2.add(jPanel11);
        jPanel11.setBounds(630, 0, 120, 30);

        PainelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1070, 790, 30));

        PlanoDeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/FM.jpg"))); // NOI18N
        PainelPrincipal.add(PlanoDeFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -450, -1, 1970));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );

        PainelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 830, 100, 560));

        PainelDeRolagem.setViewportView(PainelPrincipal);

        jMenu8.setText("Inicio");
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu8MouseClicked(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/home.png"))); // NOI18N
        jMenuItem11.setText("Inicio");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem11);

        jMenuBar1.add(jMenu8);

        jMenu1.setText("Alunos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/addp.png"))); // NOI18N
        jMenuItem1.setText("Cadastrar alunos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone_boletim_online.gif"))); // NOI18N
        jMenuItem5.setText("Criar boletim");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/aaf.png"))); // NOI18N
        jMenu5.setText("Alunos cadastrados");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/figura468.png"))); // NOI18N
        jMenuItem2.setText("Ficha pessoal");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/link1.png"))); // NOI18N
        jMenuItem3.setText("Histórico escolar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Frequência");
        jMenu5.add(jMenuItem4);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Professores");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/adda.png"))); // NOI18N
        jMenuItem6.setText("Cadastra professor");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon-entrar.png"))); // NOI18N
        jMenu6.setText("Professores cadastrados");

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icone-unidade-proposta-didatica.png"))); // NOI18N
        jMenuItem7.setText("Curriculo");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/icon_news.png"))); // NOI18N
        jMenuItem8.setText("Ficha pessoal");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem8);

        jMenu2.add(jMenu6);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ajuda");

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/1334.png"))); // NOI18N
        jMenuItem10.setText("Ajuda");
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Sair");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Cancelar.png"))); // NOI18N
        jMenuItem9.setText("Sair");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem9);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelDeRolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelDeRolagem, javax.swing.GroupLayout.PREFERRED_SIZE, 1119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jMenu8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MouseClicked
        
}//GEN-LAST:event_jMenu8MouseClicked

private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
    
}//GEN-LAST:event_jMenu8ActionPerformed

private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       CadastraAlunos t = new CadastraAlunos();
       t.setVisible(true);
       dispose();
}//GEN-LAST:event_jMenuItem1ActionPerformed

private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
CadastraProfessor t = new CadastraProfessor();
t.setVisible(true);
dispose();
}//GEN-LAST:event_jMenuItem6ActionPerformed

private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
       
}//GEN-LAST:event_jMenu7MouseClicked

private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed
          
}//GEN-LAST:event_jMenu7ActionPerformed

private void jTNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNomeCompletoActionPerformed
          String Nome = jTNomeCompleto.getText();
}//GEN-LAST:event_jTNomeCompletoActionPerformed

private void jTEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEnderecoActionPerformed
          String Endereco = jTEndereco.getText();
}//GEN-LAST:event_jTEnderecoActionPerformed

private void jTMunicipioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMunicipioActionPerformed
          String Municipio = jTMunicipio.getText();
}//GEN-LAST:event_jTMunicipioActionPerformed

private void jfCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCepActionPerformed
          String CEP = jfCep.getText(); 
}//GEN-LAST:event_jfCepActionPerformed

private void jTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTEmailActionPerformed
          String Email = jTEmail.getText();
}//GEN-LAST:event_jTEmailActionPerformed

private void jfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCpfActionPerformed
           String CPF = jfCpf.getText();
}//GEN-LAST:event_jfCpfActionPerformed

private void jfRgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfRgActionPerformed
           String RG = jfRg.getText();
}//GEN-LAST:event_jfRgActionPerformed

private void jfCargaHorariaSemanalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfCargaHorariaSemanalActionPerformed
           String CargaHoraria = jfCargaHorariaSemanal.getText();
}//GEN-LAST:event_jfCargaHorariaSemanalActionPerformed

private void jfTempoDeServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfTempoDeServicoActionPerformed
           String TempoDeServico = jfTempoDeServico.getText();
}//GEN-LAST:event_jfTempoDeServicoActionPerformed

private void jCBBancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBBancoActionPerformed
          String Banco = (String) jCBBanco.getSelectedItem();
}//GEN-LAST:event_jCBBancoActionPerformed

private void jfContaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfContaActionPerformed
          String Conta = jfConta.getText();
}//GEN-LAST:event_jfContaActionPerformed

private void jfAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfAgenciaActionPerformed
          String Agencia = jfAgencia.getText();
}//GEN-LAST:event_jfAgenciaActionPerformed

private void jCBEnsinoMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEnsinoMedioActionPerformed
          String EnsinoMedio = (String)jCBEnsinoMedio.getSelectedItem();
}//GEN-LAST:event_jCBEnsinoMedioActionPerformed

private void jTMConcluiuEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTMConcluiuEmActionPerformed
          String MConcluiuEm = jTMConcluiuEm.getText();
}//GEN-LAST:event_jTMConcluiuEmActionPerformed

private void jCBEnsinoSuperiorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBEnsinoSuperiorActionPerformed
          String EnsinoSuperior = (String)jCBEnsinoSuperior.getSelectedItem();
}//GEN-LAST:event_jCBEnsinoSuperiorActionPerformed

private void jTSConcluiuEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTSConcluiuEmActionPerformed
          String SConcluiuEm = jTSConcluiuEm.getText();
}//GEN-LAST:event_jTSConcluiuEmActionPerformed

private void jCBStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBStatusActionPerformed
          String Status = (String)jCBStatus.getSelectedItem();
}//GEN-LAST:event_jCBStatusActionPerformed

private void jCBDiretorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBDiretorActionPerformed
          String Diretor = (String)jCBDiretor.getSelectedItem();
}//GEN-LAST:event_jCBDiretorActionPerformed

private void jCBProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBProfessorActionPerformed
          String Professor = (String)jCBProfessor.getSelectedItem();
}//GEN-LAST:event_jCBProfessorActionPerformed

private void jCBOutrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBOutrosActionPerformed
          String Outros = (String)jCBOutros.getSelectedItem();
}//GEN-LAST:event_jCBOutrosActionPerformed

private void jCBNivelDeAtuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBNivelDeAtuacaoActionPerformed
          String NivelDeAtuacao = (String)jCBNivelDeAtuacao.getSelectedItem();
}//GEN-LAST:event_jCBNivelDeAtuacaoActionPerformed

private void jTDisciplinaQueLecionaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTDisciplinaQueLecionaActionPerformed
          String DisciplinaLeciona = jTDisciplinaQueLeciona.getText();
}//GEN-LAST:event_jTDisciplinaQueLecionaActionPerformed

private void jCBCursoDeLicenciaturaParaOQualFoiAprovaddoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBCursoDeLicenciaturaParaOQualFoiAprovaddoActionPerformed
          String CursoLicenciaturaAprovado = (String)jCBCursoDeLicenciaturaParaOQualFoiAprovaddo.getSelectedItem();
}//GEN-LAST:event_jCBCursoDeLicenciaturaParaOQualFoiAprovaddoActionPerformed

private void jTUniversidadeEmQueSeFormouActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUniversidadeEmQueSeFormouActionPerformed
          String UniversidadeFormou = jTUniversidadeEmQueSeFormou.getText();
}//GEN-LAST:event_jTUniversidadeEmQueSeFormouActionPerformed

private void jCBModalidadeDoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBModalidadeDoCursoActionPerformed
          String ModalidadeDoCurso = (String)jCBModalidadeDoCurso.getSelectedItem();
}//GEN-LAST:event_jCBModalidadeDoCursoActionPerformed

private void jBProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximoActionPerformed
        Curriculo sl = new Curriculo();
        sl.setVisible(true);
        dispose();
    
        //Variaveis
        String Nome = jTNomeCompleto.getText(); 
        String Endereco = jTEndereco.getText();
        String Municipio = jTMunicipio.getText();
        String CEP = jfCep.getText(); String Email = jTEmail.getText(); 
        String CPF = jfCpf.getText();String RG = jfRg.getText();
        String CargaHoraria = jfCargaHorariaSemanal.getText();
        String TempoDeServico = jfTempoDeServico.getText();
        String Banco = (String) jCBBanco.getSelectedItem();
        String Conta = jfConta.getText();
        String Agencia = jfAgencia.getText();
        String EnsinoMedio = (String)jCBEnsinoMedio.getSelectedItem();
        String MConcluiuEm = jTMConcluiuEm.getText();
        String EnsinoSuperior = (String)jCBEnsinoSuperior.getSelectedItem();
        String SConcluiuEm = jTSConcluiuEm.getText();
        String Status = (String)jCBStatus.getSelectedItem();
        String Diretor = (String)jCBDiretor.getSelectedItem();
        String Professor = (String)jCBProfessor.getSelectedItem();
        String Outros = (String)jCBOutros.getSelectedItem();
        String NivelDeAtuacao = (String)jCBNivelDeAtuacao.getSelectedItem();
        String DisciplinaLeciona = jTDisciplinaQueLeciona.getText();
        String CursoLicenciaturaAprovado = (String)jCBCursoDeLicenciaturaParaOQualFoiAprovaddo.getSelectedItem();
        String UniversidadeFormou = jTUniversidadeEmQueSeFormou.getText();
        String ModalidadeDoCurso = (String)jCBModalidadeDoCurso.getSelectedItem();
        
        
        
        //gerando pdf    
            Document documento = new Document();       
            try {
                PdfWriter.getInstance(documento, new FileOutputStream("C:\\Users\\Antonio Nunes\\Desktop\\ProjetoSecretaria\\ProjetoSecretaria\\PDF dados de professores\\"+Nome+".pdf"));
                
                //Conteudo do PDF
                documento.open();
                documento.setPageSize(PageSize.A4);
                documento.add(new Paragraph("                                                        Dados Pessoais"));
                documento.add(new Paragraph("                                                                                                                 "));
                documento.add(new Paragraph("                                                Nome completo : " +Nome));
                documento.add(new Paragraph("                                                Endereço : " +Endereco));
                documento.add(new Paragraph("                                                Municipio : " +Municipio));
                documento.add(new Paragraph("                                                CEP : " +CEP));
                documento.add(new Paragraph("                                                E-mail : " +Email));
                documento.add(new Paragraph("                                                CPF : " +CPF));
                documento.add(new Paragraph("                                                RG : " +RG));
                documento.add(new Paragraph("                                                Carga horária semanal : " + CargaHoraria));
                documento.add(new Paragraph("                                                Tempo de serviço : "+TempoDeServico));
                documento.add(new Paragraph("                                                Banco : "+Banco));
                documento.add(new Paragraph("                                                Conta : "+Conta));
                documento.add(new Paragraph("                                                Agência : "+Agencia));
                documento.add(new Paragraph("                                                Ensino médio : "+EnsinoMedio+"           Concluiu em : "+MConcluiuEm));
                documento.add(new Paragraph("                                                Ensino superior : "+EnsinoSuperior+"     Concluiu  em : "+SConcluiuEm));
                documento.add(new Paragraph("                                                Status : "+Status));
                documento.add(new Paragraph("                                                Diretor : "+Diretor));
                documento.add(new Paragraph("                                                Professor : "+Professor));
                documento.add(new Paragraph("                                                Outros : "+Outros));
                documento.add(new Paragraph("                                                Nivel de atuação como professor : "+NivelDeAtuacao));
                documento.add(new Paragraph("                                                Disciplina(s) Que leciona : "+DisciplinaLeciona));
                documento.add(new Paragraph("                                                Curso de Licienciatura para qua foi aprovado : "+CursoLicenciaturaAprovado));
                documento.add(new Paragraph("                                                Universidade em que se formou : "+UniversidadeFormou));
                documento.add(new Paragraph("                                                Modalidade do curso : "+ModalidadeDoCurso));
                documento.close();
                
            }
            catch (DocumentException | FileNotFoundException ex) {
            }
            
           
            
}//GEN-LAST:event_jBProximoActionPerformed

private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jMenuItem8ActionPerformed

private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
      try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jMenuItem7ActionPerformed

private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jMenuItem2ActionPerformed

private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
             JFileChooser sele = new JFileChooser();
        sele.showOpenDialog(null);
        File f = sele.getSelectedFile();
        String url = f.getAbsolutePath();
             ProcessBuilder p = new ProcessBuilder();
             p.command("cmd.exe","/c",url);
            p.start();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
}//GEN-LAST:event_jMenuItem3ActionPerformed

private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
Boletim e = new Boletim();
     e.setVisible(true);
     dispose();
}//GEN-LAST:event_jMenuItem5ActionPerformed

private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
TelaPrincipal f = new TelaPrincipal();
        f.setVisible(true);
        dispose();
}//GEN-LAST:event_jMenuItem11ActionPerformed

private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
          SairCadastraProfessores e = new SairCadastraProfessores();
          e.setVisible(true);
}//GEN-LAST:event_jMenuItem9ActionPerformed

private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
         //Data
         Date dataSistema = new Date();
         SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
         Data.setText(formato.format(dataSistema));
         //Hora
         timer = new Timer(1000, new cronometro());
         timer.start();
         
         
}//GEN-LAST:event_formWindowOpened

private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        SairCadastraProfessores e = new SairCadastraProfessores();
        e.setVisible(true);
}//GEN-LAST:event_jBCancelarActionPerformed

private void jBApagarTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBApagarTudoActionPerformed
         jTNomeCompleto.setText(null); 
         jTEndereco.setText(null);
         jTMunicipio.setText(null);
         jfCep.setText(null); 
          jTEmail.setText(null); 
         jfCpf.setText(null);
          jfRg.setText(null);
         jfCargaHorariaSemanal.setText(null);
         jfTempoDeServico.setText(null);
         jCBBanco.setSelectedItem(null);
        jfConta.setText(null);
         jfAgencia.setText(null);
        jCBEnsinoMedio.setSelectedItem(null);
         jTMConcluiuEm.setText(null);
        jCBEnsinoSuperior.setSelectedItem(null);
         jTSConcluiuEm.setText(null);
        jCBStatus.setSelectedItem(null);
        jCBDiretor.setSelectedItem(null);
        jCBProfessor.setSelectedItem(null);
        jCBOutros.setSelectedItem(null);
        jCBNivelDeAtuacao.setSelectedItem(null);
         jTDisciplinaQueLeciona.setText(null);
        jCBCursoDeLicenciaturaParaOQualFoiAprovaddo.setSelectedItem(null);
        jTUniversidadeEmQueSeFormou.setText(null);
        jCBModalidadeDoCurso.setSelectedItem(null);
}//GEN-LAST:event_jBApagarTudoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastraProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastraProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastraProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastraProfessor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new CadastraProfessor().setVisible(true);
            }
        });
    }
    public class cronometro implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent ae) {
            GregorianCalendar tiempo = new GregorianCalendar();
          int h, m ,s;
          h=tiempo.get(Calendar.HOUR_OF_DAY);
          m=tiempo.get(Calendar.MINUTE);
          s=tiempo.get(Calendar.SECOND);
          Hora.setText(String.valueOf(h+":"+m+":"+s));
        }

        

    }
    private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Agencia;
    private javax.swing.JLabel Banco;
    private javax.swing.JLabel CargaHorariaSemanal;
    private javax.swing.JLabel Cep;
    private javax.swing.JLabel Conta;
    private javax.swing.JLabel Cpf;
    private javax.swing.JLabel CursoDeLicenciaturaParaOQualFoiAprovado;
    private javax.swing.JLabel DadosPessoais;
    private javax.swing.JLabel Data;
    private javax.swing.JLabel Diretor;
    private javax.swing.JLabel DisciplinaQueLeciona;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel Endereco;
    private javax.swing.JLabel EnsinoMedio;
    private javax.swing.JLabel EnsinoSuperior;
    private javax.swing.JLabel Escolaridade;
    private javax.swing.JLabel Hora;
    private javax.swing.JLabel MConcluiuEm;
    private javax.swing.JLabel ModalidadeDoCurso;
    private javax.swing.JLabel Municipio;
    private javax.swing.JLabel NivelDeAtuacao;
    private javax.swing.JLabel NomeCompleto;
    private javax.swing.JLabel Outros;
    private javax.swing.JScrollPane PainelDeRolagem;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JLabel PlanoDeFundo;
    private javax.swing.JLabel Professor;
    private javax.swing.JLabel Rg;
    private javax.swing.JLabel SConcluiuEm;
    private javax.swing.JLabel Status;
    private javax.swing.JLabel TempoDeServico;
    private javax.swing.JLabel UniversidadeEmQueSeFormou;
    private javax.swing.JButton jBApagarTudo;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBProximo;
    private javax.swing.JComboBox jCBBanco;
    private javax.swing.JComboBox jCBCursoDeLicenciaturaParaOQualFoiAprovaddo;
    private javax.swing.JComboBox jCBDiretor;
    private javax.swing.JComboBox jCBEnsinoMedio;
    private javax.swing.JComboBox jCBEnsinoSuperior;
    private javax.swing.JComboBox jCBModalidadeDoCurso;
    private javax.swing.JComboBox jCBNivelDeAtuacao;
    private javax.swing.JComboBox jCBOutros;
    private javax.swing.JComboBox jCBProfessor;
    private javax.swing.JComboBox jCBStatus;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTDisciplinaQueLeciona;
    private javax.swing.JTextField jTEmail;
    private javax.swing.JTextField jTEndereco;
    private javax.swing.JTextField jTMConcluiuEm;
    private javax.swing.JTextField jTMunicipio;
    private javax.swing.JTextField jTNomeCompleto;
    private javax.swing.JTextField jTSConcluiuEm;
    private javax.swing.JTextField jTUniversidadeEmQueSeFormou;
    private javax.swing.JFormattedTextField jfAgencia;
    private javax.swing.JFormattedTextField jfCargaHorariaSemanal;
    private javax.swing.JFormattedTextField jfCep;
    private javax.swing.JFormattedTextField jfConta;
    private javax.swing.JFormattedTextField jfCpf;
    private javax.swing.JFormattedTextField jfRg;
    private javax.swing.JFormattedTextField jfTempoDeServico;
    // End of variables declaration//GEN-END:variables
}
